const express = require('express');
const axios   = require('axios');
const path    = require('path');
const fs      = require('fs');

const app      = express();
const PORT     = process.env.PORT || 3000;
const JSON_PATH = path.join(__dirname, 'tcmv2.json');

app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// ─── Load pre-parsed JSON (generated by convert.js) ──────────────────────────

let _cache     = null;
let _cacheMtime = null;

function loadData() {
  if (!fs.existsSync(JSON_PATH)) throw new Error('tcmv2.json not found — run: node convert.js');
  const mtime = fs.statSync(JSON_PATH).mtimeMs;
  if (!_cache || mtime !== _cacheMtime) {
    _cache      = JSON.parse(fs.readFileSync(JSON_PATH, 'utf8'));
    _cacheMtime = mtime;
    console.log('tcmv2.json loaded into cache');
  }
  return _cache;
}

// ─── API: Teams list ──────────────────────────────────────────────────────────

app.get('/api/teams', (req, res) => {
  try {
    const { teams } = loadData();
    res.json(teams.map(t => ({
      name:      t.name,
      total:     t.stats.total,
      scheduled: t.stats.scheduled,
      pending:   t.stats.total - t.stats.scheduled,
      release:   t.release
    })));
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ─── API: Team tickets ────────────────────────────────────────────────────────

app.get('/api/teams/:name', (req, res) => {
  try {
    const { teams, baseData } = loadData();
    const team = teams.find(t => t.name === req.params.name);
    if (!team) return res.status(404).json({ error: 'Team not found' });
    res.json({ stats: team.stats, release: team.release, tickets: team.tickets, baseData });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ─── API: Schedule (create JIRA sub-tasks) ────────────────────────────────────

app.post('/api/schedule', async (req, res) => {
  const { email, apiToken, baseUrl, tickets } = req.body;
  if (!email || !apiToken || !baseUrl)
    return res.status(400).json({ error: 'email, apiToken and baseUrl are required' });
  if (!tickets || !tickets.length)
    return res.status(400).json({ error: 'No tickets to schedule' });

  const creds   = Buffer.from(`${email}:${apiToken}`).toString('base64');
  const headers = { Authorization: `Basic ${creds}`, 'Content-Type': 'application/json', Accept: 'application/json' };
  const results = [];

  for (const t of tickets) {
    const release = req.body.release || 'N/A';

    // Fetch parent ticket description from JIRA
    let parentDescription = null;
    try {
      const parent = await axios.get(`${baseUrl}/rest/api/3/issue/${t.key}?fields=description`, { headers });
      parentDescription = parent.data?.fields?.description || null;
    } catch (e) {
      console.warn(`Could not fetch description for ${t.key}:`, e.message);
    }

    const fields = {
      project:     { key: t.projectKey },
      summary:     `Test Result for ${t.summary} - Release ${release}`,
      issuetype:   { name: 'Sub-task' },
      parent:      { key: t.key },
      duedate:     req.body.dueDate || null,
      description: parentDescription || {
        type: 'doc', version: 1,
        content: [{ type: 'paragraph', content: [{ type: 'text', text: `Test result for ${t.key} — Release: ${release}` }] }]
      }
    };
    if (t.assigneeId) fields.assignee = { accountId: t.assigneeId };

    try {
      const { data } = await axios.post(`${baseUrl}/rest/api/3/issue`, { fields }, { headers });
      results.push({ key: t.key, created: data.key, success: true });
    } catch (err) {
      const jiraErr = err.response?.data;
      const msg = jiraErr?.errorMessages?.[0]
        || (jiraErr?.errors ? JSON.stringify(jiraErr.errors) : null)
        || err.message;
      console.error(`Failed ${t.key}:`, JSON.stringify(jiraErr || err.message));
      results.push({ key: t.key, success: false, error: msg });
    }
  }
  res.json(results);
});

// Start server locally; on Vercel the exported app is used instead
if (require.main === module) {
  app.listen(PORT, () => console.log(`Regression Manager → http://localhost:${PORT}`));
}

module.exports = app;
